concommand.Add("test", function()
    local frame = vgui.Create("Dlib.Frame")
    frame:SetSize(400, 300)
    frame:Center()
    frame:SetTitle("Test Dlib.NumberWang")
    frame:MakePopup()

    local numberwang = vgui.Create("Dlib.NumberWang", frame)
    numberwang:SetPos(50, 50)
    numberwang:SetSize(300, 30)
    numberwang:SetMinMax(0, 100)
    numberwang:SetValue(50)
end)
